# Copyright 2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# https://aws.amazon.com/agreement
# SPDX-License-Identifier: MIT-0

AWSTemplateFormatVersion: 2010-09-09
Description: Deploys the necessary infrastructure CloudFormation stacksets for the Secrets Manager Backup application.

#:=====
#
# Metadata
#
#:=====

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: Resource Location Configuration
        Parameters:
          - pResourceLocationBucket
          - pResourceLocationBucketRegion
          - pResourceLocationBucketKeyPrefix
      -
        Label:
          default: Source Account Configuration
        Parameters:
          - pStackSetSourceAccountEventAccountIds
          - pStackSetSourceAccountEventRegions
      -
        Label:
          default: Backup Account Configuration
        Parameters:
          - pStackSetBackupAccountAccountId
          - pStackSetBackupAccountRegion
          - pStackSetBackupAccountReplicationRegions
      -
        Label:
          default: CloudFormation Stackset Configuration
        Parameters:
          - pStackSetAdministrationRoleName
          - pStackSetExecutionRoleName
    ParameterLabels:
      pResourceLocationBucket:
        default: Bucket Name
      pResourceLocationBucketKeyPrefix:
        default: Object Prefix
      pResourceLocationBucketRegion:
        default: Bucket Region
      pStackSetAdministrationRoleName:
        default: Administration Role Name
      pStackSetBackupAccountAccountId:
        default: Account ID
      pStackSetBackupAccountRegion:
        default: Region
      pStackSetBackupAccountReplicationRegions:
        default: Replication Regions
      pStackSetExecutionRoleName:
        default: Execution Role Name
      pStackSetSourceAccountEventAccountIds:
        default: Account IDs
      pStackSetSourceAccountEventRegions:
        default: Regions

#:=====
#
# Parameters
#
#:=====

Parameters:
  pResourceLocationBucket:
    Type: String
    AllowedPattern: ^(?!\.)(?:\.?(?!-)[a-z\d\-]+(?<!-))$
    ConstraintDescription: >-
      Parameter must contain only lower-case letters, numbers, periods, or hyphens, and may not start or end with a
      period or hyphen or have periods next to hyphens, and be between 3 and 63 characters in length.
    Description: The name of the S3 bucket that contains the deployment resource files.
    MaxLength: 63
    MinLength: 3

  pResourceLocationBucketKeyPrefix:
    Type: String
    AllowedPattern: ^[^\s]*$
    ConstraintDescription: Parameter must not contain any whitespace.
    Default: ""
    Description: >-
      The S3 object key prefix accounting for any folder structure within the bucket that contains the deployment
      resource files.  Do not include any leading or trailing slashes.
    MaxLength: 1024

  pResourceLocationBucketRegion:
    Type: String
    AllowedPattern: ^(?:(?:us(?:-gov)?|af|ap|ca|cn|eu|me|sa)-(?:central|(?:north|south)?(?:east|west)?)-\d)?$
    ConstraintDescription: Parameter must be a valid AWS Region.
    Default: ""
    Description: >-
      The region of the S3 bucket that contains the deployment resource files.  Leave blank to use the current region of
      the product.

  pStackSetAdministrationRoleName:
    Type: String
    AllowedPattern: ^[\w+=,.@\-/]+$
    ConstraintDescription: Parameter must be a valid IAM role name.
    Default: service-role/AWSControlTowerStackSetRole
    Description: >-
      The name of the administration IAM role on this account that will be used to deploy the CloudFormation stackset
      resources for this template.  Include any additional path information aside from the initial "role/".
    MaxLength: 64

  pStackSetBackupAccountAccountId:
    Type: String
    AllowedPattern: ^\d{12}$
    ConstraintDescription: Parameter must be a valid AWS account ID.
    Description: >-
      The account ID where the Secrets Manager Backup application will be deployed and where the secret backups will be
      stored.

  pStackSetBackupAccountRegion:
    Type: String
    AllowedPattern: ^(?:(?:us(?:-gov)?|af|ap|ca|cn|eu|me|sa)-(?:central|(?:north|south)?(?:east|west)?)-\d)?$
    ConstraintDescription: Parameter must be a valid AWS Region.
    Default: ""
    Description: >-
      The region where the Secrets Manager Backup application will be deployed; this is also the region where the secret
      backups will be stored.  Leave blank to use the current region of the product.

  pStackSetBackupAccountReplicationRegions:
    Type: CommaDelimitedList
    Default: ""
    Description: >-
      If region replication is desired for the backup Secrets Manager secrets, provide a comma-separated list of regions
      to serve as replication targets.

  pStackSetExecutionRoleName:
    Type: String
    AllowedPattern: ^[\w+=,.@\-]+$
    ConstraintDescription: Parameter must be a valid IAM role name.
    Default: AWSControlTowerExecution
    Description: >-
      The name of an IAM role found in all referenced accounts which will be used to deploy the CloudFormation stackset
      resources.
    MaxLength: 64

  pStackSetSourceAccountEventAccountIds:
    Type: CommaDelimitedList
    Description: >-
      A comma-separated list of account IDs which will be the source location of Secrets Manager secrets for the Secrets
      Manager Backup application.

  pStackSetSourceAccountEventRegions:
    Type: CommaDelimitedList
    Default: ""
    Description: >-
      A comma-separated list of regions in the provided source accounts which will be the source location of Secrets
      Manager secrets for the Secrets Manager Backup application.  Leave blank to only use the current region of the
      product.

#:=====
#
# Conditions
#
#:=====

Conditions:
  cUseCurrentRegionResource: !Equals [ !Ref pResourceLocationBucketRegion, "" ]
  cUseCurrentRegionStackSetBackupAccount: !Equals [ !Ref pStackSetBackupAccountRegion, "" ]
  cUseCurrentRegionStackSetSourceAccountEvent: !Equals [ !Join [ ",", !Ref pStackSetSourceAccountEventRegions ], "" ]
  cUseS3KeyPrefix: !Not [ !Equals [ !Ref pResourceLocationBucketKeyPrefix, "" ] ]

#:=====
#
# Resources
#
#:=====

Resources:
  rSecretsManagerBackupBackupAccountCloudFormationStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      AdministrationRoleARN: !Sub arn:aws:iam::${ AWS::AccountId }:role/${ pStackSetAdministrationRoleName }
      Capabilities:
        - CAPABILITY_NAMED_IAM
      Description: Deploy the Secrets Manager Backup application infrastructure into the backup account.
      ExecutionRoleName: !Ref pStackSetExecutionRoleName
      Parameters:
        -
          ParameterKey: pBackupReplicationRegions
          ParameterValue: !Join [ ",", !Ref pStackSetBackupAccountReplicationRegions ]
        -
          ParameterKey: pResourceLocationBucket
          ParameterValue: !Ref pResourceLocationBucket
        -
          ParameterKey: pResourceLocationBucketKeyPrefix
          ParameterValue: !Ref pResourceLocationBucketKeyPrefix
        -
          ParameterKey: pSourceAccountEventAccountIds
          ParameterValue: !Join [ ",", !Ref pStackSetSourceAccountEventAccountIds ]
      PermissionModel: SELF_MANAGED
      StackInstancesGroup:
        -
          DeploymentTargets:
            Accounts:
              - !Ref pStackSetBackupAccountAccountId
          Regions:
            - !If [ cUseCurrentRegionStackSetBackupAccount, !Ref AWS::Region, !Ref pStackSetBackupAccountRegion ]
      StackSetName: !Sub SecretsManagerBackup-${ AWS::StackName }
      TemplateURL: !Sub
        - https://${ pResourceLocationBucket }.s3.${ Region }.amazonaws.com/${ Prefix }secrets_manager_backup.backup_account.stackset.template.yml
        -
          Region: !If [ cUseCurrentRegionResource, !Ref AWS::Region, !Ref pResourceLocationBucketRegion ]
          Prefix: !If [ cUseS3KeyPrefix, !Sub "${ pResourceLocationBucketKeyPrefix }/" , "" ]

  rSecretsManagerBackupSourceAccountEventCloudFormationStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      AdministrationRoleARN: !Sub arn:aws:iam::${ AWS::AccountId }:role/${ pStackSetAdministrationRoleName }
      Capabilities:
        - CAPABILITY_NAMED_IAM
      Description: >-
        Deploy the EventBridge infrastructure into the backup source account to facilitate the Secrets Manager Backup
        application.
      ExecutionRoleName: !Ref pStackSetExecutionRoleName
      Parameters:
        -
          ParameterKey: pBackupAccountId
          ParameterValue: !Ref pStackSetBackupAccountAccountId
        -
          ParameterKey: pBackupRegion
          ParameterValue: !If [ cUseCurrentRegionStackSetBackupAccount, !Ref AWS::Region, !Ref pStackSetBackupAccountRegion ]
      PermissionModel: SELF_MANAGED
      StackInstancesGroup:
        -
          DeploymentTargets:
            Accounts: !Ref pStackSetSourceAccountEventAccountIds
          Regions: !If
            - cUseCurrentRegionStackSetSourceAccountEvent
            -
              - !Ref AWS::Region
            - !Ref pStackSetSourceAccountEventRegions
      StackSetName: !Sub SecretsManagerBackup-Event-${ AWS::StackName }
      TemplateURL: !Sub
        - https://${ pResourceLocationBucket }.s3.${ Region }.amazonaws.com/${ Prefix }secrets_manager_backup.source_account.event.stackset.template.yml
        -
          Region: !If [ cUseCurrentRegionResource, !Ref AWS::Region, !Ref pResourceLocationBucketRegion ]
          Prefix: !If [ cUseS3KeyPrefix, !Sub "${ pResourceLocationBucketKeyPrefix }/" , "" ]

  rSecretsManagerBackupSourceAccountRoleCloudFormationStackSet:
    Type: AWS::CloudFormation::StackSet
    DependsOn: rSecretsManagerBackupBackupAccountCloudFormationStackSet
    Properties:
      AdministrationRoleARN: !Sub arn:aws:iam::${ AWS::AccountId }:role/${ pStackSetAdministrationRoleName }
      Capabilities:
        - CAPABILITY_NAMED_IAM
      Description: >-
        Deploy the IAM infrastructure into the backup source account to facilitate the Secrets Manager Backup
        application.
      ExecutionRoleName: !Ref pStackSetExecutionRoleName
      Parameters:
        -
          ParameterKey: pBackupAccountId
          ParameterValue: !Ref pStackSetBackupAccountAccountId
        -
          ParameterKey: pBackupRegion
          ParameterValue: !If [ cUseCurrentRegionStackSetBackupAccount, !Ref AWS::Region, !Ref pStackSetBackupAccountRegion ]
      PermissionModel: SELF_MANAGED
      StackInstancesGroup:
        -
          DeploymentTargets:
            Accounts: !Ref pStackSetSourceAccountEventAccountIds
          Regions:
            - !Ref AWS::Region
      StackSetName: !Sub SecretsManagerBackup-Role-${ AWS::StackName }
      TemplateURL: !Sub
        - https://${ pResourceLocationBucket }.s3.${ Region }.amazonaws.com/${ Prefix }secrets_manager_backup.source_account.role.stackset.template.yml
        -
          Region: !If [ cUseCurrentRegionResource, !Ref AWS::Region, !Ref pResourceLocationBucketRegion ]
          Prefix: !If [ cUseS3KeyPrefix, !Sub "${ pResourceLocationBucketKeyPrefix }/" , "" ]

#:=====
#
# Outputs
#
#:=====

Outputs: {}
