# Copyright 2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# https://aws.amazon.com/agreement
# SPDX-License-Identifier: MIT-0

AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This template deploys the EventBridge resources to facilitate cross-account backups of Secrets Manager secrets in
  response to Secrets Manager API events.

#:=====
#
# Metadata
#
#:=====

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: Backup Configuration
        Parameters:
          - pBackupAccountId
          - pBackupRegion
    ParameterLabels:
      pBackupAccountId:
        default: Account ID
      pBackupRegion:
        default: Region

#:=====
#
# Parameters
#
#:=====

Parameters:
  pBackupAccountId:
    Type: String
    AllowedPattern: ^\d{12}$
    ConstraintDescription: Parameter must be a valid AWS account ID.
    Description: The account ID identified as the backup location for the Secrets Manager Backup application.

  pBackupRegion:
    Type: String
    AllowedPattern: ^(?:us(?:-gov)?|af|ap|ca|cn|eu|me|sa)-(?:central|(?:north|south)?(?:east|west)?)-\d$
    ConstraintDescription: Parameter must be a valid AWS Region.
    Description: The region identified as the backup location for the Secrets Manager Backup application.

#:=====
#
# Resources
#
#:=====

Resources:
  rSecretsManagerBackupEventsRule1:
    Type: AWS::Events::Rule
    Properties:
      Description: >-
        Event to capture Secrets Manager creation and update API events for use with the Secrets Manager Backup
        application.  Sends events to a funneling event bus in the backup account.
      EventPattern:
        detail:
          eventName:
            - CreateSecret
            - PutSecretValue
            - TagResource
            - UntagResource
            - UpdateSecret
          eventSource:
            - secretsmanager.amazonaws.com
        detail-type:
          - AWS API Call via CloudTrail
        source:
          - aws.secretsmanager
      Name: SecretsManagerBackupEvent1
      State: ENABLED
      Targets:
        -
          Arn: !Sub arn:aws:events:${ pBackupRegion }:${ pBackupAccountId }:event-bus/SecretsManagerBackupEventBus
          Id: SecretsManagerBackupEventBus
          RoleArn: !Sub arn:aws:iam::${ AWS::AccountId }:role/secrets_manager_backup/secrets_backup_event_bus_role

  rSecretsManagerBackupEventsRule2:
    Type: AWS::Events::Rule
    Properties:
      Description: >-
        Event to capture specific Secrets Manager "UpdateSecretVersionStage" events.  Sends events to a funneling event
        bus in the backup account.
      EventPattern:
        detail:
          eventName:
            - UpdateSecretVersionStage
          eventSource:
            - secretsmanager.amazonaws.com
          requestParameters:
            versionStage:
              - AWSCURRENT
        detail-type:
          - AWS API Call via CloudTrail
        source:
          - aws.secretsmanager
      Name: SecretsManagerBackupEvent2
      State: ENABLED
      Targets:
        -
          Arn: !Sub arn:aws:events:${ pBackupRegion }:${ pBackupAccountId }:event-bus/SecretsManagerBackupEventBus
          Id: SecretsManagerBackupEventBus
          RoleArn: !Sub arn:aws:iam::${ AWS::AccountId }:role/secrets_manager_backup/secrets_backup_event_bus_role

#:=====
#
# Outputs
#
#:=====

Outputs: {}
